<a href="https://colab.research.google.com/github/Dipto1971/Statistical-Analysis-Data-Science/blob/main/LAB/LAB_05/LAB_5_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!gdown --id 1g0Y27WxxsQCWWagNqUvajlre3tDOKsbM

/usr/local/lib/python3.10/dist-packages/gdown/__main__.py:140: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1g0Y27WxxsQCWWagNqUvajlre3tDOKsbM
To: /content/syntactic_car_factory_data.csv
100% 528k/528k [00:00<00:00, 34.8MB/s]

In [ ]:
import pandas as pd
df = pd.read_csv('syntactic_car_factory_data.csv')
print(df.head())

   Unnamed: 0   Sensor_1   Sensor_2   Sensor_3   Sensor_4   Sensor_5  \
0           0  54.967142  48.617357        NaN        NaN  47.658466
1           1  45.365823  45.342702  52.419623  30.867198  32.750822
2           2  64.656488  47.742237  50.675282  35.752518  44.556173
3           3  43.982934  68.522782  49.865028  39.422891        NaN
4           4  57.384666  51.713683  48.843517  46.988963  35.214780

    Sensor_6   Sensor_7   Sensor_8   Sensor_9  Sensor_10 Sensor_Status  \
0  47.658630  65.792128  57.674347  45.305256        NaN           NaN
1  44.377125  39.871689  53.142473  40.919759        NaN        Faulty
2  51.109226  38.490064  53.756980  43.993613  47.083063        Faulty
3  37.791564  52.088636  30.403299        NaN  51.968612        Faulty
4  42.801558  45.393612        NaN  53.436183  32.369598           NaN

     Shift    Line
0      NaN  Line B
1  Morning  Line A
2  Morning  Line C
3    Night  Line A
4    Night  Line A

In [ ]:
# grouped_df = df.groupby('Shift').mean()
df.groupby('Line').agg({'Sensor_1': 'mean', 'Sensor_2': 'sum'})

         Sensor_1      Sensor_2
Line
Line A  50.245822  32600.606526
Line B  50.035229  34915.548099
Line C  49.931703  34247.774064

In [ ]:
pivot = pd.pivot_table(df, values= "Sensor_1",
                       index= "Shift",
                       columns= "Line",
                       aggfunc= "mean",
                       margins= True)
print(pivot)
# pivot function: powerful tool for summerizing data

Line        Line A     Line B     Line C        All
Shift
Evening  50.725241  50.628355  49.957343  50.438237
Morning  49.505584  49.764447  50.266250  49.847506
Night    50.116501  49.646754  50.043661  49.933100
All      50.103165  50.004233  50.091410  50.064683

In [ ]:
# Lambda Functions
df['Sensor_9'] = df['Sensor_9'].apply(lambda x: 1 if x>50 else 0)
df['Sensor_9']

0       0
1       0
2       0
3       0
4       0
       ..
2995    0
2996    0
2997    0
2998    0
2999    0
Name: Sensor_9, Length: 3000, dtype: int64

In [ ]:
def adjust_sensor_value(x):
  if x>60:
    return x*1.2
  elif x<30:
    return x*0.8
  else:
    return x

df['Sensor_10'] = df['Sensor_10'].apply(adjust_sensor_value)
print(df.head())

   Unnamed: 0   Sensor_1   Sensor_2   Sensor_3   Sensor_4   Sensor_5  \
0           0  54.967142  48.617357        NaN        NaN  47.658466
1           1  45.365823  45.342702  52.419623  30.867198  32.750822
2           2  64.656488  47.742237  50.675282  35.752518  44.556173
3           3  43.982934  68.522782  49.865028  39.422891        NaN
4           4  57.384666  51.713683  48.843517  46.988963  35.214780

    Sensor_6   Sensor_7   Sensor_8  Sensor_9  Sensor_10 Sensor_Status  \
0  47.658630  65.792128  57.674347         0        NaN           NaN
1  44.377125  39.871689  53.142473         0        NaN        Faulty
2  51.109226  38.490064  53.756980         0  47.083063        Faulty
3  37.791564  52.088636  30.403299         0  51.968612        Faulty
4  42.801558  45.393612        NaN         0  32.369598           NaN

     Shift    Line
0      NaN  Line B
1  Morning  Line A
2  Morning  Line C
3    Night  Line A
4    Night  Line A